### ISSUE TITLE
Complete runpy package

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/runcards#108]
Remaining (and non-blocking) tasks for python runner:

- [x] move `pineappl` to madgraph (for a yadism run, python package should be sufficient)
- [x] `merge_grids.sh` -> `merge` 06c56d866cc77f28b2e0001abb79ab22cb59cbc4
  - this and the former depend on n3pdf/pineappl#74
- [x] update README #111 
- [x] documenting #111 
- [ ] allow for running in a generic folder (dynamically determine `paths.root`) #127 
  - it will also allow to install the package (with `pip install`) and depend on it
  - slightly depends on N3PDF/fktables#4
- [x] [redirect global `stderr`](https://github.com/NNPDF/runcards/issues/108#issuecomment-940276973) (i.e. at a very high level) 75bc9a215465ea38ce91f9f9106167df9ca03414
- [x] non-python dependency list (see following comment) #111 
- [x] add `rr list` subcommand
- [x] add `rr install` subcommand 092979c

Follows the initial setup of #104

**Comment by AleCandido** [comment]
>  * [ ]  `merge_grids.sh` -> `merge`

I should have implemented this in 06c56d866cc77f28b2e0001abb79ab22cb59cbc4 and we might be able to get rid of the `merge_grids.sh` script.

Nevertheless, I didn't have a suitable test case to check, so I've just made a fake one while developing, but it might not be faithful.
So please @cschwan, test it properly before ticking the item. There is no hurry (not even to delete the shell script).

**Comment by cschwan** [comment]
@AleCandido I just got Debian 11 (yay!) and running `./rr run TEST_RUN_SH ...` fails here:

https://github.com/NNPDF/runcards/blob/06c56d866cc77f28b2e0001abb79ab22cb59cbc4/runcardsrunner/install.py#L149

complaining that `condition` is undefined (which it is).

**Comment by AleCandido** [comment]
You're right, I broke it some days ago, it should be fixed in c82b18b48c748eb49da10ca1430924318ac9d6d5.

**Comment by cschwan** [comment]
That works again, but I get another error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cschwan/projects/runcards/runcardsrunner/cli/run.py", line 33, in subcommand
    main(dataset, theory_card, pdf)
  File "/home/cschwan/projects/runcards/runcardsrunner/cli/run.py", line 71, in main
    run_dataset(runner)
  File "/home/cschwan/projects/runcards/runcardsrunner/cli/run.py", line 128, in run_dataset
    table.convolute_grid(
  File "/home/cschwan/projects/runcards/runcardsrunner/table.py", line 43, in convolute_grid
    normalizations = loaded_grid.bin_normalizations()
  File "/home/cschwan/.cache/pypoetry/virtualenvs/runcardsrunner-Ij8RpZx_-py3.9/lib/python3.9/site-packages/pineappl/utils.py", line 17, in __getattr__
    return self._raw.__getattribute__(name)
AttributeError: 'builtins.PyGrid' object has no attribute 'bin_normalizations'
```

**Comment by AleCandido** [comment]
Unfortunately at the moment you have to run with pineappl `master`, that one has been introduced in a1fe0350b00a1129e35d680c5dfa4448a59f8fa6

**Comment by cschwan** [comment]
I see, in that case let me make another release.

**Comment by cschwan** [comment]
Here you go: https://pypi.org/project/pineappl/0.5.0_beta.3/. @AleCandido could you please tell me how I update the required version in the runner?

**Comment by AleCandido** [comment]
> Here you go: https://pypi.org/project/pineappl/0.5.0_beta.3/. @AleCandido could you please tell me how I update the required version in the runner?

For sure:
- in principle you should be able to do by running `poetry update` in the folder
- since it's a pre-release it might be a bit more complicated (it usually is more complicated for me), and I suggest to delete `poetry.lock`, manually upgrade the version in `pyproject.toml`, and finally rerun `poetry install` (it will regenerate the lock file)

**Comment by cschwan** [comment]
Both options don't work, and eventually I end up with:

```
Updating dependencies
Resolving dependencies... (0.2s)

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at /usr/lib/python3.9/json/decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│ 
```

**Comment by AleCandido** [comment]
This is not a novelty, I've seen a few times.

At the moment I don't remember why it's happening, nevertheless I tried myself and I've been able to apply the second strategy.

**Comment by cschwan** [comment]
OK, can you please commit it? I'm reverting my changes in that case. BTW: When do we rewrite it in Rust :stuck_out_tongue_winking_eye: ?

**Comment by AleCandido** [comment]
It's now published in 5e8542cbe27b642cb075626d9a6681f0f6e77979

> BTW: When do we rewrite it in Rust stuck_out_tongue_winking_eye ?

I like your style! (aside: python people are not yet there, but js people yes, [swc](https://github.com/swc-project/swc) & [parcel](https://github.com/parcel-bundler/parcel))

**Comment by cschwan** [comment]
Before we merge this I propose to change the name to something different, because 'runcards runner' is redundant. This is best displayed by the way we call it:

```
./rr run ...
```

This is basically saying: runcards runner run ..., which I also find a bit confusing. What it actually does is to generate interpolation grids, so one idea would be to call it [`gig`](https://dictionary.cambridge.org/dictionary/english/gig) (as a synonym of job):

```
./gig run ...
```

What do you think?

**Comment by AleCandido** [comment]
For me is perfectly fine, the thing has been named `runcardsrunner` exactly in lack of a better name, and the `rr` abbreviations has been chosen to make it similar to a common command (filling an empty slot of Unix) and actually to mask the redundancy.

TBH at the moment I didn't fall in love with `gig` either, but it's definitely better than `rr` (and maybe if you give some time I'll start liking it).

P.S.: consider that the first name of `rr` was actually `run` (inherited from `run.sh`), and to run with `poetry` you had to issue
```sh
poetry run run DATASET
```
and with the introduction of the subcommand it would have become
```sh
poetry run run run DATASET
```
(that's why `poetry run rr run DATASET` was already a good alternative)

**Comment by cschwan** [comment]
I'm not insisting on any name, but I think it's important that we give the tool

1. a name that better reflects what it does and that the name
2. is redudancy free.

My claim is that currently this isn't the case :smile: . So @AleCandido @felixhekhorn @scarlehoff if you have suggestions please share them!

**Comment by AleCandido** [comment]
As I said, the situation was tragic before, we brainstormed with @felixhekhorn after one lunch with really moderate results.

Just to clarify once more, I like more `gig` than `rr`. Nevertheless, let's make a poll:

[![](https://api.gh-polls.com/poll/01FKRKBBKF19B7P7CCQWS0PVD4/%60rr%60)](https://api.gh-polls.com/poll/01FKRKBBKF19B7P7CCQWS0PVD4/%60rr%60/vote)
[![](https://api.gh-polls.com/poll/01FKRKBBKF19B7P7CCQWS0PVD4/%60gig%60)](https://api.gh-polls.com/poll/01FKRKBBKF19B7P7CCQWS0PVD4/%60gig%60/vote)

**Comment by cschwan** [comment]
@AleCandido can you please upgrade the version of the pineappl Python dependency to most recent version (should be beta.4)? Otherwise I get the well-known problems with the upgraded file format.

**Comment by AleCandido** [comment]
Done :)

**Comment by cschwan** [comment]
What did you do to update the dependency? I always run into errors.

**Comment by AleCandido** [comment]
Before I simply tried `poetry update`, and it updated to `beta.3`, but for some reason it did not detect `beta.4`.

Then I did as usual:
```sh
rm -f poetry.lock
# edit pyproject.toml, manually setting beta.4
poetry update
```

For the last command, I'm pretty sure you can also use `poetry install`: essentially, the command itself is not relevant, but you want whatever `poetry` "active" command to rerun, in order to regenerate the new `poetry.lock`.

**Comment by cschwan** [comment]
When I do that, I get

```
  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at /usr/lib/python3.9/json/decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│ 
```

**Comment by AleCandido** [comment]
I'm familiar with that error: essentially every time that something goes wrong, `poetry` emits that unhelpful error.

However, since we have two different behaviors with the same procedure, I wonder if the problem might be `poetry` version.
Mine is:
```sh
❯ poetry --version
Poetry version 1.1.11
```

**Comment by felixhekhorn** [comment]
you maybe want to close this issue here and leave the open task (improved path handling) to a future PR

**Comment by AleCandido** [comment]
We have more urgent things than closing old issues, we can wait for the time being :)
